### ISSUE TITLE
How to exclude products in Woocommerce from Affiliate?

### ISSUE THREAD

**Issue by rensro** [Tapfiliate/tapfiliate-wordpress#1]
Hi! 

I'm wondering if there is a piece of code (for the thank you page) to exclude certain products from affiliate program in Woocommerce? 

Applicable on follow custom field: 

Name:                            Value:
exclude_tapfiliate          tap-exclude

Thanks in advance!

**Comment by thomask** [comment]
Hi! What you could do is the following:

1. Create a commissions array, by looping over the order items [as follows](https://gist.github.com/thomask/5de50779714f16d0817478569fa9e8db). You can place that code here: https://github.com/Tapfiliate/tapfiliate-wordpress/blob/d0b9c8a8f81a1c0ad9f64149aa533c75c09743a9/tapfiliate.php#L119
2. Make sure that you define the `$commissions_arg` variable at the start of `tapfiliate_render_woocommerce_code` and that you pass it as an extra argument to `tapfiliate_output_inline_code`;
3. Change [this line](https://github.com/Tapfiliate/tapfiliate-wordpress/blob/d0b9c8a8f81a1c0ad9f64149aa533c75c09743a9/tracking-snippet.php#L8) to `echo "tap('conversionMulti', {$external_id_arg}, {$commissions_arg}, {$options_arg});";`
