### ISSUE TITLE
Track different commission rates based on products SKU?

### ISSUE THREAD

**Issue by murtazakarimi** [Tapfiliate/tapfiliate-wordpress#3]
I wanted to know how to customize this plugin to track different commission rates that I created on Tapfilliate program settings for different products/SKU?

Thanks in advance!

**Comment by thomask** [comment]
The current version of the plugin does not support this, but this feature is slated for a future release of the plugin. For now, you could consider forking the plugin so you can amend it to your needs.

Basically, you would have to amen [the tracking snippet](https://github.com/Tapfiliate/tapfiliate-wordpress/blob/8d12582f3342ee4af821a691eb1072509e1405ac/tracking-snippet.php#L8) to use the `conversionMulti` action, [documented here](https://tapfiliate.com/docs/javascript/#conversion-multi) (and [example here](https://tapfiliate.com/docs/javascript/#tracking-multiple-commissions)).

The trick would be looping through the line items and building an array of commissions and then outputting that in the code. In case you're using WooCommerce, you can see how to loop through the line items [here](https://github.com/Tapfiliate/tapfiliate-wordpress/blob/8d12582f3342ee4af821a691eb1072509e1405ac/tapfiliate.php#L111).

Hope this helped!
